### ISSUE TITLE
AutoOpen media file causes error

### ISSUE THREAD

**Issue by spvickers** [checkdigits/spacecomputer#1]
The MediaPlayer1 component has its AutoOpen property set to true but the filename property is configured with a file location which would not be valid on most machines.  This causes an EMCIDeviceError error when the application is run.  Setting the AutoOpen property to false resolves this issue.

**Comment by checkdigits** [comment]
Oh good catch thanks @spvickers !

I have fixed this in the code and will merge the changes in a moment.

**Comment by spvickers** [comment]
Just FYI, your commit did not change the AutoOpen property of the MediaPlayer1 component to false so does not appear to have resolved the issue.

**Comment by checkdigits** [comment]
Sorry about that - I definitely changed it but I obviously made a boo boo on checking that in!  It's definitely fixed now thanks to @oldwired
